// client/src/components/StockNews.vue
<template>
  <div class="card">
    <div class="card-header">
      <h5 class="card-title mb-0">Latest News</h5>
      <p class="card-subtitle text-muted mb-0">
        Recent news and updates about {{ symbol }}
      </p>
    </div>
    <div class="card-body">
      <div v-if="isLoading" class="text-center py-4">
        Loading news...
      </div>
      <div v-else class="news-container">
        <div v-for="item in news" :key="item.id" class="card mb-3">
          <div class="card-body">
            <a 
              :href="item.url" 
              target="_blank" 
              rel="noopener noreferrer"
              class="text-decoration-none"
            >
              <h6 class="card-title">{{ item.headline }}</h6>
              <p class="card-text text-muted small mb-2">{{ item.summary }}</p>
              <div class="d-flex justify-content-between align-items-center text-muted small">
                <span>{{ item.source }}</span>
                <span>{{ new Date(item.datetime * 1000).toLocaleDateString() }}</span>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query';
import type { StockNews } from '@/lib/finnhub';

const props = defineProps<{
  symbol: string
}>();

const { data: news, isLoading } = useQuery<StockNews[]>({
  queryKey: ['news', props.symbol],
  queryFn: async () => {
    const response = await fetch(`/api/stocks/${props.symbol}/news`);
    if (!response.ok) throw new Error('Failed to fetch news');
    return response.json();
  }
});
</script>

<style scoped>
.news-container {
  max-height: 500px;
  overflow-y: auto;
}
</style>

// client/src/components/stock-news.tsx
import { useQuery } from "@tanstack/react-query";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import type { StockNews } from "@/lib/finnhub";

interface StockNewsProps {
  symbol: string;
}

export function StockNews({ symbol }: StockNewsProps) {
  const { data: news, isLoading } = useQuery<StockNews[]>({
    queryKey: [`/api/stocks/${symbol}/news`],
  });

  if (isLoading) {
    return <div>Loading news...</div>;
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Latest News</CardTitle>
        <CardDescription>Recent news and updates about {symbol}</CardDescription>
      </CardHeader>
      <CardContent>
        <ScrollArea className="h-[500px]">
          <div className="space-y-4">
            {news?.map((item) => (
              <Card key={item.id}>
                <CardContent className="p-4">
                  <a
                    href={item.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="block hover:opacity-80"
                  >
                    <h3 className="font-semibold mb-2">{item.headline}</h3>
                    <p className="text-sm text-muted-foreground mb-2">
                      {item.summary}
                    </p>
                    <div className="flex justify-between text-xs text-muted-foreground">
                      <span>{item.source}</span>
                      <span>
                        {new Date(item.datetime * 1000).toLocaleDateString()}
                      </span>
                    </div>
                  </a>
                </CardContent>
              </Card>
            ))}
          </div>
        </ScrollArea>
      </CardContent>
    </Card>
  );
}
