// client/src/components/stock-filters.tsx
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

const filterSchema = z.object({
  minPrice: z.string().optional(),
  maxPrice: z.string().optional(),
  minChangePercent: z.string().optional(),
  maxChangePercent: z.string().optional(),
  minAnalystRating: z.string().optional(),
  sectors: z.array(z.string()).optional(),
  sortBy: z.string().optional(),
  sortDir: z.enum(["asc", "desc"]).optional(),
});

type FilterValues = z.infer<typeof filterSchema>;

interface StockFiltersProps {
  onFilterChange: (filters: FilterValues) => void;
}

const SECTORS = [
  "Technology",
  "Healthcare",
  "Finance",
  "Consumer Discretionary",
  "Energy",
  "Materials",
  "Industrials",
  "Utilities",
  "Real Estate",
];

export function StockFilters({ onFilterChange }: StockFiltersProps) {
  const form = useForm<FilterValues>({
    resolver: zodResolver(filterSchema),
    defaultValues: {
      sortDir: "desc",
      minAnalystRating: "75",
    },
  });

  return (
    <Form {...form}>
      <form 
        onChange={() => onFilterChange(form.getValues())}
        className="space-y-4"
      >
        <div className="space-y-4">
          <FormField
            control={form.control}
            name="minPrice"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Min Price</FormLabel>
                <FormControl>
                  <Input type="number" placeholder="0" {...field} />
                </FormControl>
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="maxPrice"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Max Price</FormLabel>
                <FormControl>
                  <Input type="number" placeholder="1000" {...field} />
                </FormControl>
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="minAnalystRating"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Min Analyst Rating</FormLabel>
                <FormControl>
                  <Input type="number" placeholder="75" {...field} />
                </FormControl>
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="sectors"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Sector</FormLabel>
                <Select
                  onValueChange={(value) => field.onChange([value])}
                  value={field.value?.[0]}
                >
                  <FormControl>
                    <SelectTrigger>
                      <SelectValue placeholder="Select sector" />
                    </SelectTrigger>
                  </FormControl>
                  <SelectContent>
                    {SECTORS.map((sector) => (
                      <SelectItem key={sector} value={sector}>
                        {sector}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="sortBy"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Sort By</FormLabel>
                <Select onValueChange={field.onChange} value={field.value}>
                  <FormControl>
                    <SelectTrigger>
                      <SelectValue placeholder="Choose field" />
                    </SelectTrigger>
                  </FormControl>
                  <SelectContent>
                    <SelectItem value="price">Price</SelectItem>
                    <SelectItem value="changePercent">Change %</SelectItem>
                    <SelectItem value="analystRating">Analyst Rating</SelectItem>
                    <SelectItem value="volume">Volume</SelectItem>
                  </SelectContent>
                </Select>
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="sortDir"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Sort Direction</FormLabel>
                <Select onValueChange={field.onChange} value={field.value}>
                  <FormControl>
                    <SelectTrigger>
                      <SelectValue placeholder="Choose direction" />
                    </SelectTrigger>
                  </FormControl>
                  <SelectContent>
                    <SelectItem value="asc">Ascending</SelectItem>
                    <SelectItem value="desc">Descending</SelectItem>
                  </SelectContent>
                </Select>
              </FormItem>
            )}
          />
        </div>

        <Button 
          type="reset" 
          variant="outline"
          className="w-full"
          onClick={() => {
            form.reset();
            onFilterChange({});
          }}
        >
          Reset Filters
        </Button>
      </form>
    </Form>
  );
}

// client/src/components/StockFilters.vue
<template>
  <div class="card mb-4">
    <div class="card-body">
      <form @submit.prevent class="row g-3">
        <!-- Price Range -->
        <div class="col-md-3">
          <label class="form-label">Price Range</label>
          <div class="input-group">
            <input 
              type="number" 
              class="form-control" 
              v-model="filters.minPrice" 
              placeholder="Min"
            >
            <input 
              type="number" 
              class="form-control" 
              v-model="filters.maxPrice" 
              placeholder="Max"
            >
          </div>
        </div>

        <!-- Analyst Rating -->
        <div class="col-md-3">
          <label class="form-label">Min Analyst Rating</label>
          <input 
            type="number" 
            class="form-control" 
            v-model="filters.minAnalystRating" 
            placeholder="75"
          >
        </div>

        <!-- Sector -->
        <div class="col-md-3">
          <label class="form-label">Sector</label>
          <select class="form-select" v-model="filters.sectors">
            <option value="">All Sectors</option>
            <option v-for="sector in sectors" :key="sector" :value="sector">
              {{ sector }}
            </option>
          </select>
        </div>

        <!-- Sort -->
        <div class="col-md-3">
          <label class="form-label">Sort By</label>
          <select class="form-select" v-model="filters.sortBy">
            <option value="price">Price</option>
            <option value="changePercent">Change %</option>
            <option value="analystRating">Analyst Rating</option>
            <option value="volume">Volume</option>
          </select>
        </div>

        <!-- Sort Direction -->
        <div class="col-md-3">
          <label class="form-label">Sort Direction</label>
          <select class="form-select" v-model="filters.sortDir">
            <option value="asc">Ascending</option>
            <option value="desc">Descending</option>
          </select>
        </div>

        <!-- Reset Button -->
        <div class="col-12">
          <button 
            type="button" 
            class="btn btn-outline-secondary" 
            @click="resetFilters"
          >
            Reset Filters
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, watch } from 'vue';

const emit = defineEmits(['filter-change']);

const sectors = [
  'Technology',
  'Healthcare',
  'Finance',
  'Consumer Discretionary',
  'Energy',
  'Materials',
  'Industrials',
  'Utilities',
  'Real Estate'
];

const filters = reactive({
  minPrice: '',
  maxPrice: '',
  minAnalystRating: '75',
  sectors: '',
  sortBy: 'analystRating',
  sortDir: 'desc'
});

watch(filters, (newFilters) => {
  emit('filter-change', newFilters);
}, { deep: true });

function resetFilters() {
  Object.assign(filters, {
    minPrice: '',
    maxPrice: '',
    minAnalystRating: '75',
    sectors: '',
    sortBy: 'analystRating',
    sortDir: 'desc'
  });
}
</script>
